### PR TITLE
Header organization

### PR DESCRIPTION
**Pull request by 0xaf1f**
I noticed while reorganizing that f5pack includes logger.hpp, but doesn't need need to since that's included by fast5.hpp, so I removed those lines in the first commit since it's a logically separate change.

The second commit does a minimal separation. The third commit is more comprehensive, but I'm not sure whether you'd agree to it, in which case you can just cherry-pick the first two commits.

I haven't tested these myself, but I see you're running Travis, so i'll check those results and make adjustments if needed.

### CODE REVIEW

**Comment by 0xaf1f** [comment]
Ok, passes now.

**Comment by jts** [comment]
Thanks, will look at it on Monday.

**Comment by jts** [comment]
Merged, thanks for the PR!

**Comment by 0xaf1f** [comment]
Thanks! Would you mind tagging a new release?

**Comment by jts** [comment]
Done, tagged `v0.6.3`

**Comment by 0xaf1f** [comment]
Awesome. Thank you

**Pull request merged**
